from flask import Flask, jsonify
from threading import Lock

app = Flask(__name__)

text_paragraphs = [
        "The quick brown fox jumps over the lazy dog. It is a famous pangram that contains all the letters of the alphabet. This sentence is often used to test typing skills.",
        "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. It was popularized by a printing press in the early days. The text is nonsensical.",
        "Artificial intelligence is a branch of computer science that aims to create machines capable of intelligent behavior. AI can be applied in various fields such as robotics, gaming, and healthcare.",
        "The future of technology is both exciting and uncertain. Many believe that advancements in AI and machine learning will drastically change the way we live, work, and communicate with each other.",
        "Exploring the universe has always been a dream for humanity. With the advancements in space technology, humans are now closer than ever to understanding the cosmos and reaching distant planets.",
        "Renewable energy is a key component in addressing the world's growing energy needs. Solar, wind, and hydroelectric power are all sustainable options that help reduce our reliance on fossil fuels.",
        "Climate change is one of the most pressing challenges facing our planet today. Scientists have warned that global temperatures will continue to rise unless drastic measures are taken to reduce emissions.",
        "The rise of social media has had a profound impact on the way people communicate. Platforms like Facebook, Twitter, and Instagram have created new ways for individuals and brands to connect.",
        "Education is a powerful tool that helps individuals achieve their full potential. With the right opportunities and resources, anyone can unlock their ability to succeed in life and contribute to society.",
        "Sports play an important role in society by promoting physical fitness and teamwork. Whether playing professionally or for fun, sports help foster discipline, perseverance, and collaboration among individuals.",
        "The study of history helps us understand how past events have shaped the world. By learning about the triumphs and tragedies of those who came before us, we can make better decisions for the future.",
        "Health and wellness are vital aspects of life. Maintaining a balanced diet, exercising regularly, and taking care of mental health are all essential for living a long and happy life.",
        "Technology continues to evolve at a rapid pace. Innovations in fields like artificial intelligence, virtual reality, and biotechnology are transforming industries and creating new opportunities for businesses and individuals.",
        "A good night's sleep is essential for maintaining optimal health. Sleep allows the body and mind to recharge, and it plays a critical role in memory consolidation, mood regulation, and immune function.",
        "The world of business is constantly changing. Entrepreneurs must be adaptable, resilient, and innovative in order to succeed in today's competitive market. The ability to think creatively is crucial to success.",
        "Art and creativity are essential to human expression. Whether through painting, music, writing, or performance, creative works allow individuals to connect with others, express emotions, and share ideas that inspire and challenge.",
        "Sustainability is becoming increasingly important in today's world. As resources become more scarce and environmental challenges mount, finding sustainable solutions to problems like waste, energy, and food security is crucial.",
        "The human mind is incredibly powerful. By focusing on continuous learning, developing new skills, and nurturing creativity, individuals can unlock their full potential and create opportunities for personal and professional growth.",
        "Economic growth is essential for improving living standards and reducing poverty. However, it is equally important to ensure that growth is inclusive, benefiting everyone in society, and does not exacerbate inequality.",
        "Innovation is the driving force behind progress in society. By pushing boundaries, embracing new technologies, and challenging traditional ideas, innovators are helping to shape the future and solve pressing global problems.",
        "Music has a unique ability to evoke emotions and bring people together. Whether enjoying a concert, listening to a favorite album, or playing an instrument, music has the power to transcend barriers and connect individuals.",
        "The natural world is full of wonders, from towering mountains to vast oceans. Exploring nature helps us appreciate the beauty and complexity of the world around us while encouraging environmental stewardship.",
        "Human rights are fundamental to ensuring that everyone is treated with dignity and respect. Protecting and promoting these rights is essential for creating just and equitable societies where all people can thrive.",
        "The concept of time is a fascinating subject that has intrigued philosophers and scientists for centuries. Time governs our lives, yet it remains an elusive and complex concept that is still not fully understood.",
        "The Internet has revolutionized the way people access and share information. From online shopping to social media and streaming services, the digital age has made it easier than ever to connect with the world.",
        "Self-care is an important aspect of maintaining physical, mental, and emotional well-being. Taking time for oneself to relax, recharge, and reflect is essential for managing stress and achieving a balanced life.",
        "Space exploration has captured the imagination of people for generations. With missions to the Moon, Mars, and beyond, humanity continues to learn more about the cosmos and our place within it.",
        "Water is a vital resource for life. Without it, ecosystems would collapse, and human survival would be impossible. It is essential to conserve and protect water sources to ensure a sustainable future for all.",
        "Food security is an issue that affects millions of people around the world. Ensuring that everyone has access to nutritious and affordable food is crucial for promoting health and well-being.",
        "Social justice is about creating a fair and equitable society where all individuals have equal rights and opportunities. Advocating for the rights of marginalized groups is key to achieving social justice.",
        "Transportation has played a major role in shaping societies. The ability to move people and goods efficiently and safely has had a profound impact on economic development, cultural exchange, and globalization.",
        "The concept of beauty is subjective and varies across cultures. From fashion and art to architecture and design, beauty can be found in many forms, and it has the power to inspire and evoke emotions.",
        "The environment is a precious resource that requires our attention and care. As human activities continue to impact the planet, it is crucial to take steps to mitigate environmental damage and protect natural habitats.",
        "Democracy is a system of government in which power is vested in the people. It allows individuals to have a say in the decisions that affect their lives, promoting freedom and equality.",
        "Privacy is a fundamental right that protects individuals from unnecessary intrusion into their personal lives. As technology advances, safeguarding personal information and ensuring privacy in the digital world has become a growing concern.",
        "Science has the power to improve lives through discoveries and innovations. From medical breakthroughs to new technologies, science continues to shape our understanding of the world and drive progress in society.",
        "Education is a lifelong journey that empowers individuals to develop critical thinking skills, expand their knowledge, and contribute to the betterment of society. It is essential for fostering informed and engaged citizens.",
        "Psychology is the study of the human mind and behavior. By understanding how people think, feel, and act, psychologists can help improve mental health and well-being and contribute to positive societal change.",
        "Leadership is a key factor in achieving success in any organization. A good leader inspires others, sets a vision, and empowers individuals to reach their full potential while maintaining integrity and accountability.",
        "The concept of freedom is central to many political ideologies. Freedom allows individuals to make choices, express their opinions, and live their lives without unnecessary restrictions, while still respecting the rights of others.",
        "The digital age has transformed the way businesses operate. With the rise of e-commerce, cloud computing, and digital marketing, companies must adapt to an increasingly connected and technology-driven world to remain competitive.",
        "Mental health is an essential aspect of overall well-being. It affects how we think, feel, and behave, and taking care of mental health is just as important as physical health for living a fulfilling life.",
        "Sportsmanship is the practice of fair and respectful behavior in competitive activities. Whether winning or losing, sportsmanship encourages individuals to maintain good ethics and to treat opponents with respect and dignity.",
        "Humanity has made incredible advances in medicine, leading to longer life expectancies and improved quality of life. Innovations such as vaccines, surgeries, and treatments continue to transform healthcare and save lives worldwide.",
        "Public speaking is a valuable skill that can boost confidence and enhance communication abilities. Whether giving a presentation or delivering a speech, mastering the art of public speaking can lead to greater success.",
        "Innovation in the tech industry continues to accelerate, with advancements in artificial intelligence, virtual reality, and automation revolutionizing industries from healthcare to transportation. These technologies are shaping the future of society.",
        "The history of the internet is a story of growth and innovation. From its humble beginnings as a military communication tool, it has evolved into a global network that connects billions of people.",
        "The human body is a complex system of organs, tissues, and cells that work together to maintain health and perform everyday functions. Understanding the body is essential for maintaining physical well-being.",
        "Philosophy seeks to answer fundamental questions about existence, knowledge, ethics, and the mind. By exploring different philosophical perspectives, individuals can gain a deeper understanding of the world and their place within it.",
        "Artificial intelligence and automation are transforming industries and the workforce. As machines take on more tasks, there is an increasing need for reskilling and adapting to new technological advancements.",
        "The power of storytelling has been recognized for centuries. Stories help convey ideas, emotions, and experiences that connect people across cultures and generations, making them a powerful tool for communication and understanding.",
        "Public transportation systems play a key role in urban planning. Buses, trains, and subways help reduce traffic congestion, lower carbon emissions, and provide an efficient way for people to travel within cities.",
        "The concept of time has fascinated humans for centuries. Whether measuring seconds or centuries, time is an essential part of our lives, helping us organize our daily routines and understand the passage of history.",
        "Culture is the shared beliefs, values, and practices that define a group of people. It influences how individuals think, behave, and interact, and it plays a major role in shaping identity.",
        "Globalization has led to increased interconnectedness between nations and cultures. While this has created new opportunities for trade, travel, and communication, it has also raised concerns about cultural homogenization and inequality.",
        "The Internet of Things (IoT) is a network of devices that are connected to the internet and can communicate with each other. It is transforming industries such as healthcare, manufacturing, and transportation.",
        "In order to achieve success, perseverance is key. Overcoming obstacles and maintaining focus on long-term goals can lead to personal growth and accomplishment, even when faced with challenges or setbacks.",
        "Sustainability is a critical issue facing our planet. Protecting the environment, conserving natural resources, and reducing carbon footprints are essential for ensuring that future generations have a livable and thriving world.",
        "The environment is a precious resource that requires our attention and care. As human activities continue to impact the planet, it is crucial to take steps to mitigate environmental damage and protect natural habitats.",
        "Democracy is a system of government in which power is vested in the people. It allows individuals to have a say in the decisions that affect their lives, promoting freedom and equality.",
        "Privacy is a fundamental right that protects individuals from unnecessary intrusion into their personal lives. As technology advances, safeguarding personal information and ensuring privacy in the digital world has become a growing concern.",
        "Science has the power to improve lives through discoveries and innovations. From medical breakthroughs to new technologies, science continues to shape our understanding of the world and drive progress in society.",
        "Education is a lifelong journey that empowers individuals to develop critical thinking skills, expand their knowledge, and contribute to the betterment of society. It is essential for fostering informed and engaged citizens.",
        "Psychology is the study of the human mind and behavior. By understanding how people think, feel, and act, psychologists can help improve mental health and well-being and contribute to positive societal change.",
        "Leadership is a key factor in achieving success in any organization. A good leader inspires others, sets a vision, and empowers individuals to reach their full potential while maintaining integrity and accountability.",
        "The concept of freedom is central to many political ideologies. Freedom allows individuals to make choices, express their opinions, and live their lives without unnecessary restrictions, while still respecting the rights of others.",
        "The digital age has transformed the way businesses operate. With the rise of e-commerce, cloud computing, and digital marketing, companies must adapt to an increasingly connected and technology-driven world to remain competitive.",
        "Mental health is an essential aspect of overall well-being. It affects how we think, feel, and behave, and taking care of mental health is just as important as physical health for living a fulfilling life.",
        "Sportsmanship is the practice of fair and respectful behavior in competitive activities. Whether winning or losing, sportsmanship encourages individuals to maintain good ethics and to treat opponents with respect and dignity.",
        "Humanity has made incredible advances in medicine, leading to longer life expectancies and improved quality of life. Innovations such as vaccines, surgeries, and treatments continue to transform healthcare and save lives worldwide.",
        "Public speaking is a valuable skill that can boost confidence and enhance communication abilities. Whether giving a presentation or delivering a speech, mastering the art of public speaking can lead to greater success.",
        "Innovation in the tech industry continues to accelerate, with advancements in artificial intelligence, virtual reality, and automation revolutionizing industries from healthcare to transportation. These technologies are shaping the future of society.",
        "The history of the internet is a story of growth and innovation. From its humble beginnings as a military communication tool, it has evolved into a global network that connects billions of people.",
        "The human body is a complex system of organs, tissues, and cells that work together to maintain health and perform everyday functions. Understanding the body is essential for maintaining physical well-being.",
        "Philosophy seeks to answer fundamental questions about existence, knowledge, ethics, and the mind. By exploring different philosophical perspectives, individuals can gain a deeper understanding of the world and their place within it.",
        "Artificial intelligence and automation are transforming industries and the workforce. As machines take on more tasks, there is an increasing need for reskilling and adapting to new technological advancements.",
        "The power of storytelling has been recognized for centuries. Stories help convey ideas, emotions, and experiences that connect people across cultures and generations, making them a powerful tool for communication and understanding.",
        "Public transportation systems play a key role in urban planning. Buses, trains, and subways help reduce traffic congestion, lower carbon emissions, and provide an efficient way for people to travel within cities.",
        "The concept of time has fascinated humans for centuries. Whether measuring seconds or centuries, time is an essential part of our lives, helping us organize our daily routines and understand the passage of history.",
        "Culture is the shared beliefs, values, and practices that define a group of people. It influences how individuals think, behave, and interact, and it plays a major role in shaping identity.",
        "Globalization has led to increased interconnectedness between nations and cultures. While this has created new opportunities for trade, travel, and communication, it has also raised concerns about cultural homogenization and inequality.",
        "The Internet of Things (IoT) is a network of devices that are connected to the internet and can communicate with each other. It is transforming industries such as healthcare, manufacturing, and transportation.",
        "In order to achieve success, perseverance is key. Overcoming obstacles and maintaining focus on long-term goals can lead to personal growth and accomplishment, even when faced with challenges or setbacks.",
        "Sustainability is a critical issue facing our planet. Protecting the environment, conserving natural resources, and reducing carbon footprints are essential for ensuring that future generations have a livable and thriving world.",
        "The environment is a precious resource that requires our attention and care. As human activities continue to impact the planet, it is crucial to take steps to mitigate environmental damage and protect natural habitats.",
        "Democracy is a system of government in which power is vested in the people. It allows individuals to have a say in the decisions that affect their lives, promoting freedom and equality.",
        "Privacy is a fundamental right that protects individuals from unnecessary intrusion into their personal lives. As technology advances, safeguarding personal information and ensuring privacy in the digital world has become a growing concern.",
        "Science has the power to improve lives through discoveries and innovations. From medical breakthroughs to new technologies, science continues to shape our understanding of the world and drive progress in society.",
        "Education is a lifelong journey that empowers individuals to develop critical thinking skills, expand their knowledge, and contribute to the betterment of society. It is essential for fostering informed and engaged citizens.",
        "Psychology is the study of the human mind and behavior. By understanding how people think, feel, and act, psychologists can help improve mental health and well-being and contribute to positive societal change.",
        "Leadership is a key factor in achieving success in any organization. A good leader inspires others, sets a vision, and empowers individuals to reach their full potential while maintaining integrity and accountability.",
        "The concept of freedom is central to many political ideologies. Freedom allows individuals to make choices, express their opinions, and live their lives without unnecessary restrictions, while still respecting the rights of others.",
        "The digital age has transformed the way businesses operate. With the rise of e-commerce, cloud computing, and digital marketing, companies must adapt to an increasingly connected and technology-driven world to remain competitive.",
        "Mental health is an essential aspect of overall well-being. It affects how we think, feel, and behave, and taking care of mental health is just as important as physical health for living a fulfilling life.",
        "Sportsmanship is the practice of fair and respectful behavior in competitive activities. Whether winning or losing, sportsmanship encourages individuals to maintain good ethics and to treat opponents with respect and dignity.",
        "Humanity has made incredible advances in medicine, leading to longer life expectancies and improved quality of life. Innovations such as vaccines, surgeries, and treatments continue to transform healthcare and save lives worldwide.",
        "Public speaking is a valuable skill that can boost confidence and enhance communication abilities. Whether giving a presentation or delivering a speech, mastering the art of public speaking can lead to greater success.",
        "Innovation in the tech industry continues to accelerate, with advancements in artificial intelligence, virtual reality, and automation revolutionizing industries from healthcare to transportation. These technologies are shaping the future of society.",
        "The history of the internet is a story of growth and innovation. From its humble beginnings as a military communication tool, it has evolved into a global network that connects billions of people.",
        "The human body is a complex system of organs, tissues, and cells that work together to maintain health and perform everyday functions. Understanding the body is essential for maintaining physical well-being.",
        "Philosophy seeks to answer fundamental questions about existence, knowledge, ethics, and the mind. By exploring different philosophical perspectives, individuals can gain a deeper understanding of the world and their place within it.",
        "Artificial intelligence and automation are transforming industries and the workforce. As machines take on more tasks, there is an increasing need for reskilling and adapting to new technological advancements.",
        "The power of storytelling has been recognized for centuries. Stories help convey ideas, emotions, and experiences that connect people across cultures and generations, making them a powerful tool for communication and understanding.",
        "Public transportation systems play a key role in urban planning. Buses, trains, and subways help reduce traffic congestion, lower carbon emissions, and provide an efficient way for people to travel within cities.",
        "The concept of time has fascinated humans for centuries. Whether measuring seconds or centuries, time is an essential part of our lives, helping us organize our daily routines and understand the passage of history.",
        "Culture is the shared beliefs, values, and practices that define a group of people. It influences how individuals think, behave, and interact, and it plays a major role in shaping identity.",
        "Globalization has led to increased interconnectedness between nations and cultures. While this has created new opportunities for trade, travel, and communication, it has also raised concerns about cultural homogenization and inequality.",
        "The Internet of Things (IoT) is a network of devices that are connected to the internet and can communicate with each other. It is transforming industries such as healthcare, manufacturing, and transportation.",
        "In order to achieve success, perseverance is key. Overcoming obstacles and maintaining focus on long-term goals can lead to personal growth and accomplishment, even when faced with challenges or setbacks.",
        "Sustainability is a critical issue facing our planet. Protecting the environment, conserving natural resources, and reducing carbon footprints are essential for ensuring that future generations have a livable and thriving world."
     ]
     
lock = Lock()

@app.route('/api/text/<index>', methods=['GET'])
def get_text(index):
    text = text_paragraphs[int(index)]
    return text

if __name__ == '__main__':
    app.run(host='localhost', port='5031')
   